server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://140.238.187.194:3100/loki/api/v1/push

scrape_configs:
  - job_name: stdout_logs
    static_configs:
      - targets:
          - localhost
      - labels:
          job: varlogs
          __path__: /var/log/*.log

      - labels:
          job: weblogs
          __path__: /logs/*.log
